name: Deploy JSON Schema

on:
    push:
        branches: main
        paths:
            - 'config.schema.json'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Create deployment directory
              run: |
                  mkdir -p public
                  cp config.schema.json public/

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: public

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
